name: skbs_app
description: "Приложение СКБС для сотрудников, табеля, задач, выплат и документов."
publish_to: 'none'
version: 1.3.3+7

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^8.1.0
  excel: ^4.0.6
  universal_html: ^2.3.0
  archive: ^3.6.1
  pdf: ^3.11.3
  supabase_flutter: ^2.8.3
  shared_preferences: ^2.3.3
  intl: ^0.19.0
  docx_template: ^0.4.0
  file_saver:
    path: third_party/file_saver
  mime_type: ^1.0.0
  file_selector: ^1.0.4
  path_provider: ^2.1.5
  url_launcher: ^6.3.1
  flutter_local_notifications: ^18.0.1
  firebase_core: ^4.4.0
  firebase_messaging: ^16.2.0
  timezone: ^0.10.0
  record: ^6.2.0
  flutter_secure_storage: ^10.0.0
  flutter_svg: ^2.2.0
  image: ^4.3.0
  collection: ^1.19.1
  web: ^1.1.1
  js: ^0.7.2
  excel_archive:
    path: third_party/excel_archive

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/app_logo.png
    - assets/app_logo_dark.png
    - assets/app_logo_light.png
    - assets/avatar_foreman_base.png
    - assets/avatar_foreman_silver.png
    - assets/avatar_foreman_gold.png
    - assets/templates/
