create table if not exists public.object_geofences (
  id uuid primary key default gen_random_uuid(),
  company_id uuid not null,
  object_id uuid not null references public.objects(id) on delete cascade,
  latitude double precision not null check (latitude between -90 and 90),
  longitude double precision not null check (longitude between -180 and 180),
  radius_m integer not null default 250 check (radius_m between 30 and 5000),
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (company_id, object_id)
);

create table if not exists public.employee_work_shifts (
  id uuid primary key default gen_random_uuid(),
  company_id uuid not null,
  employee_id uuid not null references public.employees(id) on delete cascade,
  task_id uuid references public.tasks(id) on delete set null,
  object_id uuid not null references public.objects(id) on delete restrict,
  work_date date not null default current_date,
  status text not null default 'active' check (status in ('active', 'completed', 'cancelled')),
  started_at timestamptz not null default now(),
  ended_at timestamptz,
  start_latitude double precision not null check (start_latitude between -90 and 90),
  start_longitude double precision not null check (start_longitude between -180 and 180),
  start_accuracy_m double precision not null check (start_accuracy_m >= 0),
  start_distance_m double precision not null check (start_distance_m >= 0),
  end_latitude double precision check (end_latitude between -90 and 90),
  end_longitude double precision check (end_longitude between -180 and 180),
  end_accuracy_m double precision check (end_accuracy_m >= 0),
  permission_scope text not null default 'unknown'
    check (permission_scope in ('always', 'while_in_use', 'web_foreground', 'unknown')),
  tracking_mode text not null default 'web_foreground'
    check (tracking_mode in ('native_background', 'web_foreground')),
  route_point_count integer not null default 0 check (route_point_count >= 0),
  last_point_at timestamptz,
  started_by uuid references auth.users(id) on delete set null,
  ended_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check ((status = 'active' and ended_at is null) or status <> 'active')
);

create unique index if not exists employee_work_shifts_one_active_per_employee
  on public.employee_work_shifts (company_id, employee_id)
  where status = 'active';

create index if not exists employee_work_shifts_employee_date_idx
  on public.employee_work_shifts (company_id, employee_id, work_date desc, started_at desc);

create index if not exists employee_work_shifts_object_date_idx
  on public.employee_work_shifts (company_id, object_id, work_date desc);

create table if not exists public.employee_work_shift_points (
  id bigint generated by default as identity primary key,
  company_id uuid not null,
  shift_id uuid not null references public.employee_work_shifts(id) on delete cascade,
  employee_id uuid not null references public.employees(id) on delete cascade,
  recorded_at timestamptz not null,
  latitude double precision not null check (latitude between -90 and 90),
  longitude double precision not null check (longitude between -180 and 180),
  accuracy_m double precision not null check (accuracy_m >= 0),
  altitude_m double precision,
  speed_mps double precision,
  heading_deg double precision,
  is_mock boolean not null default false,
  source text not null default 'device' check (source in ('device', 'start', 'finish')),
  created_at timestamptz not null default now()
);

create index if not exists employee_work_shift_points_route_idx
  on public.employee_work_shift_points (shift_id, recorded_at, id);

create index if not exists employee_work_shift_points_employee_idx
  on public.employee_work_shift_points (company_id, employee_id, recorded_at desc);

alter table public.object_geofences enable row level security;
alter table public.employee_work_shifts enable row level security;
alter table public.employee_work_shift_points enable row level security;

revoke all on public.object_geofences from anon, authenticated;
revoke all on public.employee_work_shifts from anon, authenticated;
revoke all on public.employee_work_shift_points from anon, authenticated;

grant all on public.object_geofences to service_role;
grant all on public.employee_work_shifts to service_role;
grant all on public.employee_work_shift_points to service_role;
grant usage, select on sequence public.employee_work_shift_points_id_seq to service_role;
